# Generated by Django 5.2.1 on 2025-05-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('nascimento', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.TextField()),
                ('profissao', models.TextField()),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
