# Generated by Django 5.2.1 on 2025-05-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_clientes_alter_vendas_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='qualidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('idade', models.IntegerField()),
                ('data', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('estado_civil', models.TextField()),
                ('num_compras', models.IntegerField()),
                ('renda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prod_comprado', models.TextField()),
            ],
        ),
    ]
