# Generated by Django 5.2.1 on 2025-05-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_qualidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualidade',
            name='telefone',
            field=models.CharField(max_length=40),
        ),
    ]
