# Generated by Django 5.2.1 on 2025-06-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_alter_qualidade_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.TextField()),
                ('quantidade', models.IntegerField()),
                ('preco_uni', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
