# Generated by Django 5.2.1 on 2025-06-04 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendas.clientes'),
        ),
    ]
