# Generated by Django 5.2.1 on 2025-06-04 01:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_vendas_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualidade',
            name='email',
        ),
        migrations.RemoveField(
            model_name='qualidade',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='qualidade',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='qualidade',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='qualidade',
            name='renda',
        ),
        migrations.RemoveField(
            model_name='qualidade',
            name='telefone',
        ),
        migrations.AddField(
            model_name='clientes',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='renda',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='qualidade',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendas.clientes'),
        ),
        migrations.AddField(
            model_name='qualidade',
            name='nota',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='qualidade',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
