# Generated by Django 5.2.1 on 2025-06-04 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_remove_qualidade_email_remove_qualidade_estado_civil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.estoque'),
        ),
    ]
